% Script to use convert2swc to convert all .mat (generated by fastmarching) in a folder to swc
function convert2swcall(path2convert)
    [pathstr, ~, ~] = fileparts(mfilename('fullpath'));
    addpath(fullfile(pathstr, '..', 'util'));
    addpath(fullfile(pathstr, '..', 'lib', 'dir2'));
    addpath(fullfile(pathstr, '..', '..', '..', 'v3d', 'v3d_external', 'matlab_io_basicdatatype'));

	disp(['Searching path...', path2convert])
    fnames = dir2(path2convert, '*.mat', '-r');
    disp(fnames)
    for i = 1 : numel(fnames)   
    	f = fnames(i);
    	f = f.name;

    	% if numel(f) > 4 && strcmp(f(end-3:end), '.mat')
		fprintf('Converting %s\n', f);
		d = load(fullfile(path2convert, f));
		branch2swc(d.S, fullfile(path2convert, f));
    	% end
    end
end
